POST http://localhost:3000/musics
Content-Type: application/json

{
    "src": "adai.mp3",
    "title": "Adai",
    "duration": "1:35",
    "author": "Qurmangazy",
    "year": "1880",
    "genre": "folk"
}