GET http://localhost:3000/users/664a8f77ddb0f8eda03d4ff1/musics?page=1&limit=5
authorization: 123123123

###
GET http://localhost:3000/users/664a9f01132d7865159960f1/playlist
authorization: 123123123

###
DELETE http://localhost:3000/users/664a9f01132d7865159960f1/music
authorization: 123123123
Content-Type: application/json

{
    "title": "Adai",
    "author": "Qurmangazy"
}


###
POST http://localhost:3000/users/playlist
authorization: 123123123
Content-Type: application/json

{
    "title": "Adai",
    "author": "Qurmangazy",
    "userId": "664a9f01132d7865159960f1"
}

